kmake: Add support for KMAKE_BUILD_DIR env var
Allow the user to customize the path to the build directory via the
environment variable KMAKE_BUILD_DIR.

diff --git a/linux-kernel-tools/kmake b/linux-kernel-tools/kmake
--- a/linux-kernel-tools/kmake
+++ b/linux-kernel-tools/kmake
@@ -10,6 +10,12 @@ separate build tree without having to type too much. This is basically an alias
 for:
 
     make O=build -j\$(nproc) <make_args>
+
+The following environment variables can be used to customize the behavior:
+
+    KMAKE_BUILD_DIR
+        Use a build directory different from \"build\". The path must be
+        relative to the toplevel directory.
 "
 }
 
@@ -46,12 +52,14 @@ while (( $# > 0 )); do
     esac
 done
 
+KMAKE_BUILD_DIR=${KMAKE_BUILD_DIR:-build}
+
 if ! is_linux_kernel; then
     err 'This does not appear to be a linux kernel.' >&2
 fi
 
-if ! [[ -f build/.config ]]; then
-    err 'Missing build/.config file.'
+if ! [[ -f "${KMAKE_BUILD_DIR}/.config" ]]; then
+    err "Missing \"${KMAKE_BUILD_DIR}/.config\" file."
 fi
 
-exec make O=build -j$(nproc) "$@"
+exec make O="$KMAKE_BUILD_DIR" -j$(nproc) "$@"
